# Generated by Django 4.1 on 2022-08-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukoly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukol',
            name='stav',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
