# Generated by Django 4.1 on 2022-08-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukoly', '0002_ukol_stav'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukol',
            name='jmeno_autora',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ukol',
            name='stav',
            field=models.BooleanField(default=False),
        ),
    ]
