# Generated by Django 4.1 on 2022-09-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ukoly', '0004_ukol_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ukol',
            name='jmeno_autora',
        ),
    ]
